package com.reyaz.core.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF196B52)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA5F2D3)
val onPrimaryContainerLight = Color(0xFF00513C)
val secondaryLight = Color(0xFF4C6359)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCEE9DB)
val onSecondaryContainerLight = Color(0xFF354C42)
val tertiaryLight = Color(0xFF3F6375)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC2E8FD)
val onTertiaryContainerLight = Color(0xFF264B5C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
//val backgroundLight = Color(0xFFF5FBF6)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF171D1A)
//val surfaceLight = Color(0xFFF5FBF6)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF171D1A)
val surfaceVariantLight = Color(0xFFDBE5DE)
val onSurfaceVariantLight = Color(0xFF404944)
val outlineLight = Color(0xFF707974)
val outlineVariantLight = Color(0xFFBFC9C2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322F)
val inverseOnSurfaceLight = Color(0xFFECF2ED)
val inversePrimaryLight = Color(0xFF8AD6B8)
val surfaceDimLight = Color(0xFFD5DBD7)
val surfaceBrightLight = Color(0xFFF5FBF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F0)
val surfaceContainerLight = Color(0xFFE9EFEA)
val surfaceContainerHighLight = Color(0xFFE4EAE5)
val surfaceContainerHighestLight = Color(0xFFDEE4DF)

val primaryDark = Color(0xFF8AD6B8)
//val primaryDark = Color(0xFF15E8B4)
val onPrimaryDark = Color(0xFF003829)
val primaryContainerDark = Color(0xFF00513C)
val onPrimaryContainerDark = Color(0xFFA5F2D3)
val secondaryDark = Color(0xFFB3CCC0)
val onSecondaryDark = Color(0xFF1E352C)
val secondaryContainerDark = Color(0xFF354C42)
val onSecondaryContainerDark = Color(0xFFCEE9DB)
val tertiaryDark = Color(0xFFA7CCE0)
val onTertiaryDark = Color(0xFF0A3445)
val tertiaryContainerDark = Color(0xFF264B5C)
val onTertiaryContainerDark = Color(0xFFC2E8FD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF000000)
//val backgroundDark = Color(0xFF0F1512)
val onBackgroundDark = Color(0xFFDEE4DF)
//val surfaceDark = Color(0xFF0F1512)
val surfaceDark = Color(0xFF000000)
val onSurfaceDark = Color(0xFFDEE4DF)
val surfaceVariantDark = Color(0xFF404944)
val onSurfaceVariantDark = Color(0xFFBFC9C2)
val outlineDark = Color(0xFF89938D)
val outlineVariantDark = Color(0xFF404944)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DF)
val inverseOnSurfaceDark = Color(0xFF2C322F)
val inversePrimaryDark = Color(0xFF196B52)
val surfaceDimDark = Color(0xFF0F1512)
val surfaceBrightDark = Color(0xFF343B37)
val surfaceContainerLowestDark = Color(0xFF0A0F0D)
val surfaceContainerLowDark = Color(0xFF171D1A)
val surfaceContainerDark = Color(0xFF1B211E)
val surfaceContainerHighDark = Color(0xFF252B28)
val surfaceContainerHighestDark = Color(0xFF303633)

val brandColorLight = Color(0xFF535A92)
val onBrandColorLight = Color(0xFFFFFFFF)
val brandColorContainerLight = Color(0xFFDFE0FF)
val onBrandColorContainerLight = Color(0xFF3B4279)

val gainerColorLight = Color(0xFF388E3C)
val loserColorLight = Color(0xFFD32F2F)

val gainerColorDark = Color(0xFF81C784)
val loserColorDark = Color(0xFFE57373)

val brandColorDark = Color(0xFFBCC2FF)
val onBrandColorDark = Color(0xFF242B61)
val brandColorContainerDark = Color(0xFF3B4279)
val onBrandColorContainerDark = Color(0xFFDFE0FF)

